LOCAL_PATH := vendor/samsung/xcover
PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/system/lib/libril.so:system/lib/libril.so \
	$(LOCAL_PATH)/system/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \
	$(LOCAL_PATH)/system/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
	$(LOCAL_PATH)/system/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \
	$(LOCAL_PATH)/system/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so \
	$(LOCAL_PATH)/system/lib/gst/libgstaacdec.so:system/lib/gst/libgstaacdec.so \
	$(LOCAL_PATH)/system/lib/gst/libgstalsasink.so:system/lib/gst/libgstalsasink.so \
	$(LOCAL_PATH)/system/lib/gst/libgstapedemux.so:system/lib/gst/libgstapedemux.so \
	$(LOCAL_PATH)/system/lib/gst/libgstapp.so:system/lib/gst/libgstapp.so \
	$(LOCAL_PATH)/system/lib/gst/libgstasfdemux.so:system/lib/gst/libgstasfdemux.so \
	$(LOCAL_PATH)/system/lib/gst/libgstaudiocachesink.so:system/lib/gst/libgstaudiocachesink.so \
	$(LOCAL_PATH)/system/lib/gst/libgstaudioconvert.so:system/lib/gst/libgstaudioconvert.so \
	$(LOCAL_PATH)/system/lib/gst/libgstaudioflingersink.so:system/lib/gst/libgstaudioflingersink.so \
	$(LOCAL_PATH)/system/lib/gst/libgstaudiorate.so:system/lib/gst/libgstaudiorate.so \
	$(LOCAL_PATH)/system/lib/gst/libgstaudioresample.so:system/lib/gst/libgstaudioresample.so \
	$(LOCAL_PATH)/system/lib/gst/libgstaudiotestsrc.so:system/lib/gst/libgstaudiotestsrc.so \
	$(LOCAL_PATH)/system/lib/gst/libgstautoconvert.so:system/lib/gst/libgstautoconvert.so \
	$(LOCAL_PATH)/system/lib/gst/libgstautodetect.so:system/lib/gst/libgstautodetect.so \
	$(LOCAL_PATH)/system/lib/gst/libgstavi.so:system/lib/gst/libgstavi.so \
	$(LOCAL_PATH)/system/lib/gst/libgstcoreelements.so:system/lib/gst/libgstcoreelements.so \
	$(LOCAL_PATH)/system/lib/gst/libgstcoreindexers.so:system/lib/gst/libgstcoreindexers.so \
	$(LOCAL_PATH)/system/lib/gst/libgstdecodebin.so:system/lib/gst/libgstdecodebin.so \
	$(LOCAL_PATH)/system/lib/gst/libgstdecodebin2.so:system/lib/gst/libgstdecodebin2.so \
	$(LOCAL_PATH)/system/lib/gst/libgstffmpeg.so:system/lib/gst/libgstffmpeg.so \
	$(LOCAL_PATH)/system/lib/gst/libgstffmpegcolorspace.so:system/lib/gst/libgstffmpegcolorspace.so \
	$(LOCAL_PATH)/system/lib/gst/libgstflac.so:system/lib/gst/libgstflac.so \
	$(LOCAL_PATH)/system/lib/gst/libgstflumpegdemux.so:system/lib/gst/libgstflumpegdemux.so \
	$(LOCAL_PATH)/system/lib/gst/libgstflv.so:system/lib/gst/libgstflv.so \
	$(LOCAL_PATH)/system/lib/gst/libgstgdp.so:system/lib/gst/libgstgdp.so \
	$(LOCAL_PATH)/system/lib/gst/libgsth263dec.so:system/lib/gst/libgsth263dec.so \
	$(LOCAL_PATH)/system/lib/gst/libgsth264dec.so:system/lib/gst/libgsth264dec.so \
	$(LOCAL_PATH)/system/lib/gst/libgstid3demux.so:system/lib/gst/libgstid3demux.so \
	$(LOCAL_PATH)/system/lib/gst/libgstippaacenc.so:system/lib/gst/libgstippaacenc.so \
	$(LOCAL_PATH)/system/lib/gst/libgstippamrnbdec.so:system/lib/gst/libgstippamrnbdec.so \
	$(LOCAL_PATH)/system/lib/gst/libgstippamrnbenc.so:system/lib/gst/libgstippamrnbenc.so \
	$(LOCAL_PATH)/system/lib/gst/libgstippamrwbdec.so:system/lib/gst/libgstippamrwbdec.so \
	$(LOCAL_PATH)/system/lib/gst/libgstippamrwbenc.so:system/lib/gst/libgstippamrwbenc.so \
	$(LOCAL_PATH)/system/lib/gst/libgstippmpeg2dec.so:system/lib/gst/libgstippmpeg2dec.so \
	$(LOCAL_PATH)/system/lib/gst/libgstmatroska.so:system/lib/gst/libgstmatroska.so \
	$(LOCAL_PATH)/system/lib/gst/libgstmjpegdec.so:system/lib/gst/libgstmjpegdec.so \
	$(LOCAL_PATH)/system/lib/gst/libgstmp3dec.so:system/lib/gst/libgstmp3dec.so \
	$(LOCAL_PATH)/system/lib/gst/libgstmpeg4dec.so:system/lib/gst/libgstmpeg4dec.so \
	$(LOCAL_PATH)/system/lib/gst/libgstmpegaudioparse.so:system/lib/gst/libgstmpegaudioparse.so \
	$(LOCAL_PATH)/system/lib/gst/libgstmulaw.so:system/lib/gst/libgstmulaw.so \
	$(LOCAL_PATH)/system/lib/gst/libgstplaybin.so:system/lib/gst/libgstplaybin.so \
	$(LOCAL_PATH)/system/lib/gst/libgstqtdemux.so:system/lib/gst/libgstqtdemux.so \
	$(LOCAL_PATH)/system/lib/gst/libgstrtp.so:system/lib/gst/libgstrtp.so \
	$(LOCAL_PATH)/system/lib/gst/libgstrtpmanager.so:system/lib/gst/libgstrtpmanager.so \
	$(LOCAL_PATH)/system/lib/gst/libgstrtpmux.so:system/lib/gst/libgstrtpmux.so \
	$(LOCAL_PATH)/system/lib/gst/libgstrtsp.so:system/lib/gst/libgstrtsp.so \
	$(LOCAL_PATH)/system/lib/gst/libgstsouphttpsrc.so:system/lib/gst/libgstsouphttpsrc.so \
	$(LOCAL_PATH)/system/lib/gst/libgstsubparse.so:system/lib/gst/libgstsubparse.so \
	$(LOCAL_PATH)/system/lib/gst/libgstsurfaceflingersink.so:system/lib/gst/libgstsurfaceflingersink.so \
	$(LOCAL_PATH)/system/lib/gst/libgsttcp.so:system/lib/gst/libgsttcp.so \
	$(LOCAL_PATH)/system/lib/gst/libgsttypefindfunctions.so:system/lib/gst/libgsttypefindfunctions.so \
	$(LOCAL_PATH)/system/lib/gst/libgstudp.so:system/lib/gst/libgstudp.so \
	$(LOCAL_PATH)/system/lib/gst/libgstvideorate.so:system/lib/gst/libgstvideorate.so \
	$(LOCAL_PATH)/system/lib/gst/libgstvideoscale.so:system/lib/gst/libgstvideoscale.so \
	$(LOCAL_PATH)/system/lib/gst/libgstvideotestsrc.so:system/lib/gst/libgstvideotestsrc.so \
	$(LOCAL_PATH)/system/lib/gst/libgstvmetadec.so:system/lib/gst/libgstvmetadec.so \
	$(LOCAL_PATH)/system/lib/gst/libgstvolume.so:system/lib/gst/libgstvolume.so \
	$(LOCAL_PATH)/system/lib/gst/libgstwavparse.so:system/lib/gst/libgstwavparse.so \
	$(LOCAL_PATH)/system/lib/gst/libgstwmadec.so:system/lib/gst/libgstwmadec.so \
	$(LOCAL_PATH)/system/lib/gst/libgstwmvdec.so:system/lib/gst/libgstwmvdec.so \
	$(LOCAL_PATH)/system/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
	$(LOCAL_PATH)/system/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
	$(LOCAL_PATH)/system/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
	$(LOCAL_PATH)/system/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
	$(LOCAL_PATH)/system/lib/soundfx/libbundlewrapper.so:system/lib/soundfx/libbundlewrapper.so \
	$(LOCAL_PATH)/system/lib/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
	$(LOCAL_PATH)/system/lib/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \
	$(LOCAL_PATH)/system/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
	$(LOCAL_PATH)/system/etc/audio/LVVEFS_Rx_Configuration.txt:system/etc/audio/LVVEFS_Rx_Configuration.txt \
	$(LOCAL_PATH)/system/etc/audio/LVVEFS_Tx_Configuration.txt:system/etc/audio/LVVEFS_Tx_Configuration.txt \
	$(LOCAL_PATH)/system/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt \
	$(LOCAL_PATH)/system/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt \
	$(LOCAL_PATH)/system/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
	$(LOCAL_PATH)/system/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
	$(LOCAL_PATH)/system/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt \
	$(LOCAL_PATH)/system/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt \
	$(LOCAL_PATH)/system/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
	$(LOCAL_PATH)/system/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
	$(LOCAL_PATH)/system/etc/firmware/mrvl/sd8787_uapsta.bin:system/etc/firmware/mrvl/sd8787_uapsta.bin \
	$(LOCAL_PATH)/system/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin:system/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin \
	$(LOCAL_PATH)/system/etc/firmware/mrvl/WlanCalData_ext.conf:system/etc/firmware/mrvl/WlanCalData_ext.conf \
	$(LOCAL_PATH)/system/etc/labtool/FEM_RFMD_5365.ini:system/etc/labtool/FEM_RFMD_5365.ini \
	$(LOCAL_PATH)/system/etc/labtool/SetUp.ini:system/etc/labtool/SetUp.ini \
	$(LOCAL_PATH)/system/etc/mpdc/config/config_internal.txt:system/etc/mpdc/config/config_internal.txt \
	$(LOCAL_PATH)/system/etc/mpdc/config/manzano.xml:system/etc/mpdc/config/manzano.xml \
	$(LOCAL_PATH)/system/etc/mpdc/config/mohawk.xml:system/etc/mpdc/config/mohawk.xml \
	$(LOCAL_PATH)/system/etc/mpdc/config/pxa3xx.xml:system/etc/mpdc/config/pxa3xx.xml \
	$(LOCAL_PATH)/system/etc/mpdc/config/pxa93x.xml:system/etc/mpdc/config/pxa93x.xml \
	$(LOCAL_PATH)/system/etc/mpdc/config/pxa168.xml:system/etc/mpdc/config/pxa168.xml \
	$(LOCAL_PATH)/system/etc/mpdc/config/pxa510.xml:system/etc/mpdc/config/pxa510.xml \
	$(LOCAL_PATH)/system/etc/mpdc/config/pxa610.xml:system/etc/mpdc/config/pxa610.xml \
	$(LOCAL_PATH)/system/etc/mpdc/config/pxa940.xml:system/etc/mpdc/config/pxa940.xml \
	$(LOCAL_PATH)/system/etc/mpdc/config/pxa955.xml:system/etc/mpdc/config/pxa955.xml \
	$(LOCAL_PATH)/system/etc/mpdc/config/system_info.xml:system/etc/mpdc/config/system_info.xml \
	$(LOCAL_PATH)/system/etc/mpdc/help/mohawk/event:system/etc/mpdc/help/mohawk/event \
	$(LOCAL_PATH)/system/etc/mpdc/help/pxa3xx/event:system/etc/mpdc/help/pxa3xx/event \
	$(LOCAL_PATH)/system/etc/mpdc/help/pxa93x/event:system/etc/mpdc/help/pxa93x/event \
	$(LOCAL_PATH)/system/etc/mpdc/help/pxa168/event:system/etc/mpdc/help/pxa168/event \
	$(LOCAL_PATH)/system/etc/mpdc/help/pxa510/event:system/etc/mpdc/help/pxa510/event \
	$(LOCAL_PATH)/system/etc/mpdc/help/pxa610/event:system/etc/mpdc/help/pxa610/event \
	$(LOCAL_PATH)/system/etc/mpdc/help/pxa940/event:system/etc/mpdc/help/pxa940/event \
	$(LOCAL_PATH)/system/etc/mpdc/help/pxa955/event:system/etc/mpdc/help/pxa955/event \
	$(LOCAL_PATH)/system/etc/mpdc/all:system/etc/mpdc/all \
	$(LOCAL_PATH)/system/etc/mpdc/cm_options:system/etc/mpdc/cm_options \
	$(LOCAL_PATH)/system/etc/mpdc/css_options:system/etc/mpdc/css_options \
	$(LOCAL_PATH)/system/etc/mpdc/hs_options:system/etc/mpdc/hs_options \
	$(LOCAL_PATH)/system/etc/mpdc/pt_list:system/etc/mpdc/pt_list \
	$(LOCAL_PATH)/system/etc/permissions/android.hardware.camera.autofocus.xml:system/etc/permissions/android.hardware.camera.autofocus.xml \
	$(LOCAL_PATH)/system/etc/permissions/android.hardware.camera.flash-autofocus.xml:system/etc/permissions/android.hardware.camera.flash-autofocus.xml \
	$(LOCAL_PATH)/system/etc/permissions/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
	$(LOCAL_PATH)/system/etc/permissions/android.hardware.sensor.proximity.xml:system/etc/permissions/android.hardware.sensor.proximity.xml \
	$(LOCAL_PATH)/system/etc/permissions/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml \
	$(LOCAL_PATH)/system/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml \
	$(LOCAL_PATH)/system/etc/permissions/android.hardware.touchscreen.multitouch.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.xml \
	$(LOCAL_PATH)/system/etc/permissions/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	$(LOCAL_PATH)/system/etc/permissions/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml \
	$(LOCAL_PATH)/system/etc/permissions/com.android.location.provider.xml:system/etc/permissions/com.android.location.provider.xml \
	$(LOCAL_PATH)/system/etc/permissions/com.marvell.android.mtil_library.xml:system/etc/permissions/com.marvell.android.mtil_library.xml \
	$(LOCAL_PATH)/system/etc/permissions/com.samsung.android.sec_platform_library.xml:system/etc/permissions/com.samsung.android.sec_platform_library.xml \
	$(LOCAL_PATH)/system/etc/permissions/com.samsung.device.xml:system/etc/permissions/com.samsung.device.xml \
	$(LOCAL_PATH)/system/etc/permissions/com.sec.android.keystring.xml:system/etc/permissions/com.sec.android.keystring.xml \
	$(LOCAL_PATH)/system/etc/permissions/com.sec.android.riloemhook.xml:system/etc/permissions/com.sec.android.riloemhook.xml \
	$(LOCAL_PATH)/system/etc/permissions/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
	$(LOCAL_PATH)/system/etc/permissions/hw-features.xml:system/etc/permissions/hw-features.xml \
	$(LOCAL_PATH)/system/etc/permissions/platform.xml:system/etc/permissions/platform.xml \
	$(LOCAL_PATH)/system/etc/permissions/seccamera.xml:system/etc/permissions/seccamera.xml \
	$(LOCAL_PATH)/system/etc/permissions/sec_feature.xml:system/etc/permissions/sec_feature.xml \
	$(LOCAL_PATH)/system/etc/permissions/sw-features.xml:system/etc/permissions/sw-features.xml \
	$(LOCAL_PATH)/system/etc/permissions/touchwiz.xml:system/etc/permissions/touchwiz.xml \
	$(LOCAL_PATH)/system/etc/ppp/ip-down-vpn:system/etc/ppp/ip-down-vpn \
	$(LOCAL_PATH)/system/etc/ppp/ip-up-vpn:system/etc/ppp/ip-up-vpn \
	$(LOCAL_PATH)/system/etc/security/cacerts.bks:system/etc/security/cacerts.bks \
	$(LOCAL_PATH)/system/etc/security/otacerts.zip:system/etc/security/otacerts.zip \
	$(LOCAL_PATH)/system/etc/updatecmds/google_generic_update.txt:system/etc/updatecmds/google_generic_update.txt \
	$(LOCAL_PATH)/system/etc/AGPS_CA.pem:system/etc/AGPS_CA.pem \
	$(LOCAL_PATH)/system/etc/apns-conf.xml:system/etc/apns-conf.xml \
	$(LOCAL_PATH)/system/etc/FileMonitorService.conf:system/etc/FileMonitorService.conf \
	$(LOCAL_PATH)/system/etc/gps.conf:system/etc/gps.conf \
	$(LOCAL_PATH)/system/etc/gst.conf:system/etc/gst.conf \
	$(LOCAL_PATH)/system/etc/hosts:system/etc/hosts \
	$(LOCAL_PATH)/system/etc/install-recovery.sh:system/etc/install-recovery.sh \
	$(LOCAL_PATH)/system/etc/media_profiles.xml:system/etc/media_profiles.xml \
	$(LOCAL_PATH)/system/etc/mrvl.cfg:system/etc/mrvl.cfg \
	$(LOCAL_PATH)/system/etc/NOTICE.html.gz:system/etc/NOTICE.html.gz \
	$(LOCAL_PATH)/system/etc/nwk_info.xml:system/etc/nwk_info.xml \
	$(LOCAL_PATH)/system/etc/nwk_info.xml:system/etc/nwk_info.xml \
	$(LOCAL_PATH)/system/etc/poweron.ogg:system/etc/poweron.ogg \
	$(LOCAL_PATH)/system/etc/pvplayer.cfg:system/etc/pvplayer.cfg \
	$(LOCAL_PATH)/system/etc/sirfgps.conf:system/etc/sirfgps.conf \
	$(LOCAL_PATH)/system/etc/spn-conf.xml:system/etc/spn-conf.xml \
	$(LOCAL_PATH)/system/etc/vold.fstab:system/etc/vold.fstab \
	$(LOCAL_PATH)/system/etc/wifidirect_defaults.conf:system/etc/wifidirect_defaults.conf \
	$(LOCAL_PATH)/system/bin/am:system/bin/am \
	$(LOCAL_PATH)/system/bin/applypatch:system/bin/applypatch \
	$(LOCAL_PATH)/system/bin/app_process:system/bin/app_process \
	$(LOCAL_PATH)/system/bin/app_process.orig:system/bin/app_process.orig \
	$(LOCAL_PATH)/system/bin/bmgr:system/bin/bmgr \
	$(LOCAL_PATH)/system/bin/bmmtest:system/bin/bmmtest \
	$(LOCAL_PATH)/system/bin/bootanimation:system/bin/bootanimationxxxx \
	$(LOCAL_PATH)/system/bin/bugreport:system/bin/bugreport \
	$(LOCAL_PATH)/system/bin/cat:system/bin/cat \
	$(LOCAL_PATH)/system/bin/charging_mode:system/bin/charging_mode \
	$(LOCAL_PATH)/system/bin/chmod:system/bin/chmod \
	$(LOCAL_PATH)/system/bin/chown:system/bin/chown \
	$(LOCAL_PATH)/system/bin/cmp:system/bin/cmp \
	$(LOCAL_PATH)/system/bin/cryptsetup:system/bin/cryptsetup \
	$(LOCAL_PATH)/system/bin/dalvikvm:system/bin/dalvikvm \
	$(LOCAL_PATH)/system/bin/date:system/bin/date \
	$(LOCAL_PATH)/system/bin/dbus-daemon:system/bin/dbus-daemon \
	$(LOCAL_PATH)/system/bin/dd:system/bin/dd \
	$(LOCAL_PATH)/system/bin/debuggerd:system/bin/debuggerd \
	$(LOCAL_PATH)/system/bin/dexopt:system/bin/dexopt \
	$(LOCAL_PATH)/system/bin/df:system/bin/df \
	$(LOCAL_PATH)/system/bin/dhcp_announce:system/bin/dhcp_announce \
	$(LOCAL_PATH)/system/bin/dhcpcd:system/bin/dhcpcd \
	$(LOCAL_PATH)/system/bin/dmesg:system/bin/dmesg \
	$(LOCAL_PATH)/system/bin/dnsmasq:system/bin/dnsmasq \
	$(LOCAL_PATH)/system/bin/drm_android_siso_test:system/bin/drm_android_siso_test \
	$(LOCAL_PATH)/system/bin/drm_sqlite3_test:system/bin/drm_sqlite3_test \
	$(LOCAL_PATH)/system/bin/dumpmesg:system/bin/dumpmesg \
	$(LOCAL_PATH)/system/bin/dumpstate:system/bin/dumpstate \
	$(LOCAL_PATH)/system/bin/dumpsys:system/bin/dumpsys \
	$(LOCAL_PATH)/system/bin/dvz:system/bin/dvz \
	$(LOCAL_PATH)/system/bin/FileMonitorService:system/bin/FileMonitorService \
	$(LOCAL_PATH)/system/bin/fsck_msdos:system/bin/fsck_msdos \
	$(LOCAL_PATH)/system/bin/getevent:system/bin/getevent \
	$(LOCAL_PATH)/system/bin/getprop:system/bin/getprop \
	$(LOCAL_PATH)/system/bin/gst-inspect-0.10:system/bin/gst-inspect-0.10 \
	$(LOCAL_PATH)/system/bin/gst-launch-0.10:system/bin/gst-launch-0.10 \
	$(LOCAL_PATH)/system/bin/gst-run-0.10:system/bin/gst-run-0.10 \
	$(LOCAL_PATH)/system/bin/gst-typefind-0.10:system/bin/gst-typefind-0.10 \
	$(LOCAL_PATH)/system/bin/gst-xmlinspect-0.10:system/bin/gst-xmlinspect-0.10 \
	$(LOCAL_PATH)/system/bin/gzip:system/bin/gzip \
	$(LOCAL_PATH)/system/bin/hd:system/bin/hd \
	$(LOCAL_PATH)/system/bin/id:system/bin/id \
	$(LOCAL_PATH)/system/bin/ifconfig:system/bin/ifconfig \
	$(LOCAL_PATH)/system/bin/iftop:system/bin/iftop \
	$(LOCAL_PATH)/system/bin/ime:system/bin/ime \
	$(LOCAL_PATH)/system/bin/input:system/bin/input \
	$(LOCAL_PATH)/system/bin/insmod:system/bin/insmod \
	$(LOCAL_PATH)/system/bin/installd:system/bin/installd \
	$(LOCAL_PATH)/system/bin/install-recovery.sh:system/bin/install-recovery.sh \
	$(LOCAL_PATH)/system/bin/ioctl:system/bin/ioctl \
	$(LOCAL_PATH)/system/bin/ionice:system/bin/ionice \
	$(LOCAL_PATH)/system/bin/ip:system/bin/ip \
	$(LOCAL_PATH)/system/bin/iptables:system/bin/iptables \
	$(LOCAL_PATH)/system/bin/keystore:system/bin/keystore \
	$(LOCAL_PATH)/system/bin/kill:system/bin/kill \
	$(LOCAL_PATH)/system/bin/linker:system/bin/linker \
	$(LOCAL_PATH)/system/bin/ln:system/bin/ln \
	$(LOCAL_PATH)/system/bin/load_mpdc.sh:system/bin/load_mpdc.sh \
	$(LOCAL_PATH)/system/bin/log:system/bin/log \
	$(LOCAL_PATH)/system/bin/logcat:system/bin/logcat \
	$(LOCAL_PATH)/system/bin/logwrapper:system/bin/logwrapper \
	$(LOCAL_PATH)/system/bin/ls:system/bin/ls \
	$(LOCAL_PATH)/system/bin/lsmod:system/bin/lsmod \
	$(LOCAL_PATH)/system/bin/lsof:system/bin/lsof \
	$(LOCAL_PATH)/system/bin/MarvellWirelessDaemon:system/bin/MarvellWirelessDaemon \
	$(LOCAL_PATH)/system/bin/mcfg:system/bin/mcfg \
	$(LOCAL_PATH)/system/bin/mediaserver:system/bin/mediaserver \
	$(LOCAL_PATH)/system/bin/memsicd:system/bin/memsicd \
	$(LOCAL_PATH)/system/bin/mfgloader:system/bin/mfgloader \
	$(LOCAL_PATH)/system/bin/mkdir:system/bin/mkdir \
	$(LOCAL_PATH)/system/bin/monkey:system/bin/monkey \
	$(LOCAL_PATH)/system/bin/mount:system/bin/mount \
	$(LOCAL_PATH)/system/bin/mpdc:system/bin/mpdc \
	$(LOCAL_PATH)/system/bin/mpdc_d:system/bin/mpdc_d \
	$(LOCAL_PATH)/system/bin/mpdc_svr:system/bin/mpdc_svr \
	$(LOCAL_PATH)/system/bin/mrvlhcitool:system/bin/mrvlhcitool \
	$(LOCAL_PATH)/system/bin/mtpd:system/bin/mtpd \
	$(LOCAL_PATH)/system/bin/mv:system/bin/mv \
	$(LOCAL_PATH)/system/bin/mwu:system/bin/mwu \
	$(LOCAL_PATH)/system/bin/mwu_cli:system/bin/mwu_cli \
	$(LOCAL_PATH)/system/bin/nandread:system/bin/nandread \
	$(LOCAL_PATH)/system/bin/ndc:system/bin/ndc \
	$(LOCAL_PATH)/system/bin/netcfg:system/bin/netcfg \
	$(LOCAL_PATH)/system/bin/netd:system/bin/netd \
	$(LOCAL_PATH)/system/bin/netstat:system/bin/netstat \
	$(LOCAL_PATH)/system/bin/newfs_msdos:system/bin/newfs_msdos \
	$(LOCAL_PATH)/system/bin/notify:system/bin/notify \
	$(LOCAL_PATH)/system/bin/npsmobex:system/bin/npsmobex \
	$(LOCAL_PATH)/system/bin/omx_tests:system/bin/omx_tests \
	$(LOCAL_PATH)/system/bin/passcodemanager:system/bin/passcodemanager \
	$(LOCAL_PATH)/system/bin/ping:system/bin/ping \
	$(LOCAL_PATH)/system/bin/playlpm:system/bin/playlpm \
	$(LOCAL_PATH)/system/bin/playsound:system/bin/playsound \
	$(LOCAL_PATH)/system/bin/pm:system/bin/pm \
	$(LOCAL_PATH)/system/bin/pppd:system/bin/pppd \
	$(LOCAL_PATH)/system/bin/printenv:system/bin/printenv \
	$(LOCAL_PATH)/system/bin/ps:system/bin/ps \
	$(LOCAL_PATH)/system/bin/pxidle:system/bin/pxidle \
	$(LOCAL_PATH)/system/bin/pxksymaddr:system/bin/pxksymaddr \
	$(LOCAL_PATH)/system/bin/qrngd:system/bin/qrngd \
	$(LOCAL_PATH)/system/bin/qrngtest:system/bin/qrngtest \
	$(LOCAL_PATH)/system/bin/racoon:system/bin/racoon \
	$(LOCAL_PATH)/system/bin/reboot:system/bin/reboot \
	$(LOCAL_PATH)/system/bin/recovery:system/bin/recovery \
	$(LOCAL_PATH)/system/bin/redbend_ua:system/bin/redbend_ua \
	$(LOCAL_PATH)/system/bin/renice:system/bin/renice \
	$(LOCAL_PATH)/system/bin/rfkill:system/bin/rfkill \
	$(LOCAL_PATH)/system/bin/rild:system/bin/rild \
	$(LOCAL_PATH)/system/bin/rm:system/bin/rm \
	$(LOCAL_PATH)/system/bin/rmdir:system/bin/rmdir \
	$(LOCAL_PATH)/system/bin/rmmod:system/bin/rmmod \
	$(LOCAL_PATH)/system/bin/route:system/bin/route \
	$(LOCAL_PATH)/system/bin/schedtest:system/bin/schedtest \
	$(LOCAL_PATH)/system/bin/schedtop:system/bin/schedtop \
	$(LOCAL_PATH)/system/bin/sdcard:system/bin/sdcard \
	$(LOCAL_PATH)/system/bin/sendevent:system/bin/sendevent \
	$(LOCAL_PATH)/system/bin/service:system/bin/service \
	$(LOCAL_PATH)/system/bin/servicemanager:system/bin/servicemanager \
	$(LOCAL_PATH)/system/bin/setconsole:system/bin/setconsole \
	$(LOCAL_PATH)/system/bin/setprop:system/bin/setprop \
	$(LOCAL_PATH)/system/bin/sh:system/bin/sh \
	$(LOCAL_PATH)/system/bin/sleep:system/bin/sleep \
	$(LOCAL_PATH)/system/bin/smd:system/bin/smd \
	$(LOCAL_PATH)/system/bin/start:system/bin/start \
	$(LOCAL_PATH)/system/bin/stop:system/bin/stop \
	$(LOCAL_PATH)/system/bin/surfaceflinger:system/bin/surfaceflinger \
	$(LOCAL_PATH)/system/bin/svc:system/bin/svc \
	$(LOCAL_PATH)/system/bin/sync:system/bin/sync \
	$(LOCAL_PATH)/system/bin/system_server:system/bin/system_server \
	$(LOCAL_PATH)/system/bin/tc:system/bin/tc \
	$(LOCAL_PATH)/system/bin/test_client:system/bin/test_client \
	$(LOCAL_PATH)/system/bin/toolbox:system/bin/toolbox \
	$(LOCAL_PATH)/system/bin/top:system/bin/top \
	$(LOCAL_PATH)/system/bin/uap.conf:system/bin/uap.conf \
	$(LOCAL_PATH)/system/bin/umount:system/bin/umount \
	$(LOCAL_PATH)/system/bin/unload_mpdc.sh:system/bin/unload_mpdc.sh \
	$(LOCAL_PATH)/system/bin/uptime:system/bin/uptime \
	$(LOCAL_PATH)/system/bin/vdc:system/bin/vdc \
	$(LOCAL_PATH)/system/bin/vmstat:system/bin/vmstat \
	$(LOCAL_PATH)/system/bin/vold:system/bin/vold \
	$(LOCAL_PATH)/system/bin/watchprops:system/bin/watchprops \
	$(LOCAL_PATH)/system/bin/wifidir_init.conf:system/bin/wifidir_init.conf \
	$(LOCAL_PATH)/system/bin/wipe:system/bin/wipe \
	$(LOCAL_PATH)/system/bin/wlandutservice:system/bin/wlandutservice \
	$(LOCAL_PATH)/system/bin/wpa_supplicant:system/bin/wpa_supplicant \
	$(LOCAL_PATH)/system/lib/libacc.so:system/lib/libacc.so \
	$(LOCAL_PATH)/system/lib/libaccelcal.so:system/lib/libaccelcal.so \
	$(LOCAL_PATH)/system/lib/libaccsensorcal.so:system/lib/libaccsensorcal.so \
	$(LOCAL_PATH)/system/lib/libaccsensorcaltest.so:system/lib/libaccsensorcaltest.so \
	$(LOCAL_PATH)/system/lib/libandroid.so:system/lib/libandroid.so \
	$(LOCAL_PATH)/system/lib/libandroid_runtime.so:system/lib/libandroid_runtime.so \
	$(LOCAL_PATH)/system/lib/libandroid_servers.so:system/lib/libandroid_servers.so \
	$(LOCAL_PATH)/system/lib/libarccamera.so:system/lib/libarccamera.so \
	$(LOCAL_PATH)/system/lib/libasound.so:system/lib/libasound.so \
	$(LOCAL_PATH)/system/lib/libaudio.so:system/lib/libaudio.so \
	$(LOCAL_PATH)/system/lib/libaudioeffect_jni.so:system/lib/libaudioeffect_jni.so \
	$(LOCAL_PATH)/system/lib/libaudioflinger.so:system/lib/libaudioflinger.so \
	$(LOCAL_PATH)/system/lib/libaudiopath.so:system/lib/libaudiopath.so \
	$(LOCAL_PATH)/system/lib/libaudiopolicy.so:system/lib/libaudiopolicy.so \
	$(LOCAL_PATH)/system/lib/libbinder.so:system/lib/libbinder.so \
	$(LOCAL_PATH)/system/lib/libbluedroid.so:system/lib/libbluedroid.so \
	$(LOCAL_PATH)/system/lib/libbmm.so:system/lib/libbmm.so \
	$(LOCAL_PATH)/system/lib/libbtstereo.so:system/lib/libbtstereo.so \
	$(LOCAL_PATH)/system/lib/libbtstereo_server.so:system/lib/libbtstereo_server.so \
	$(LOCAL_PATH)/system/lib/libc.so:system/lib/libc.so \
	$(LOCAL_PATH)/system/lib/libcamera.so:system/lib/libcamera.so \
	$(LOCAL_PATH)/system/lib/libcamera_client.so:system/lib/libcamera_client.so \
	$(LOCAL_PATH)/system/lib/libcameraservice.so:system/lib/libcameraservice.so \
	$(LOCAL_PATH)/system/lib/libCaMotion.so:system/lib/libCaMotion.so \
	$(LOCAL_PATH)/system/lib/libcaps.so:system/lib/libcaps.so \
	$(LOCAL_PATH)/system/lib/libcodecaacdec.so:system/lib/libcodecaacdec.so \
	$(LOCAL_PATH)/system/lib/libcodecaacenc.so:system/lib/libcodecaacenc.so \
	$(LOCAL_PATH)/system/lib/libcodecamrnbdec.so:system/lib/libcodecamrnbdec.so \
	$(LOCAL_PATH)/system/lib/libcodecamrnbenc.so:system/lib/libcodecamrnbenc.so \
	$(LOCAL_PATH)/system/lib/libcodecamrwbdec.so:system/lib/libcodecamrwbdec.so \
	$(LOCAL_PATH)/system/lib/libcodecamrwbenc.so:system/lib/libcodecamrwbenc.so \
	$(LOCAL_PATH)/system/lib/libcodecg711.so:system/lib/libcodecg711.so \
	$(LOCAL_PATH)/system/lib/libcodech263dec.so:system/lib/libcodech263dec.so \
	$(LOCAL_PATH)/system/lib/libcodech263enc.so:system/lib/libcodech263enc.so \
	$(LOCAL_PATH)/system/lib/libcodech264dec.so:system/lib/libcodech264dec.so \
	$(LOCAL_PATH)/system/lib/libcodech264enc.so:system/lib/libcodech264enc.so \
	$(LOCAL_PATH)/system/lib/libcodecjpegdec.so:system/lib/libcodecjpegdec.so \
	$(LOCAL_PATH)/system/lib/libcodecjpegenc.so:system/lib/libcodecjpegenc.so \
	$(LOCAL_PATH)/system/lib/libcodecmp3dec.so:system/lib/libcodecmp3dec.so \
	$(LOCAL_PATH)/system/lib/libcodecmpeg2dec.so:system/lib/libcodecmpeg2dec.so \
	$(LOCAL_PATH)/system/lib/libcodecmpeg4dec.so:system/lib/libcodecmpeg4dec.so \
	$(LOCAL_PATH)/system/lib/libcodecmpeg4enc.so:system/lib/libcodecmpeg4enc.so \
	$(LOCAL_PATH)/system/lib/libcodecvmetadec.so:system/lib/libcodecvmetadec.so \
	$(LOCAL_PATH)/system/lib/libcodecvmetaenc.so:system/lib/libcodecvmetaenc.so \
	$(LOCAL_PATH)/system/lib/libcodecwmadec.so:system/lib/libcodecwmadec.so \
	$(LOCAL_PATH)/system/lib/libcodecwmvdec.so:system/lib/libcodecwmvdec.so \
	$(LOCAL_PATH)/system/lib/libcrypto.so:system/lib/libcrypto.so \
	$(LOCAL_PATH)/system/lib/libctest.so:system/lib/libctest.so \
	$(LOCAL_PATH)/system/lib/libstagefright.so:system/lib/libstagefright.so \
	$(LOCAL_PATH)/system/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
	$(LOCAL_PATH)/system/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
	$(LOCAL_PATH)/system/lib/libstagefright_avc_common.so:system/lib/libstagefright_avc_common.so \
	$(LOCAL_PATH)/system/lib/libstagefright_enc_common.so:system/lib/libstagefright_enc_common.so \
	$(LOCAL_PATH)/system/lib/libstagefright_foundation.so:system/lib/libstagefright_foundation.so \
	$(LOCAL_PATH)/system/lib/libstagefright_amrnb_common.so:system/lib/libstagefright_amrnb_common.so \
	$(LOCAL_PATH)/system/lib/libstagefright_color_conversion.so:system/lib/libstagefright_color_conversion.so \
	$(LOCAL_PATH)/system/lib/libstagefright_hardware_renderer.so:system/lib/libstagefright_hardware_renderer.so \
	$(LOCAL_PATH)/system/lib/libriloemhook.so:system/lib/libriloemhook.so \
	$(LOCAL_PATH)/system/lib/libreference-ril.so:system/lib/libreference-ril.so \
	$(LOCAL_PATH)/system/lib/libEGL.so:system/lib/libEGL.so \
	$(LOCAL_PATH)/system/lib/libGLESv2.so:system/lib/libGLESv2.so \
	$(LOCAL_PATH)/system/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
	$(LOCAL_PATH)/system/lib/libscreencapture.so:system/lib/libscreencapture.so \
	$(LOCAL_PATH)/system/lib/libopencore_mp4local.so:system/lib/libopencore_mp4local.so \
	$(LOCAL_PATH)/system/lib/libopencore_mp4localreg.so:system/lib/libopencore_mp4localreg.so \
	$(LOCAL_PATH)/system/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
	$(LOCAL_PATH)/system/usr/keylayout/sec_jack.kl:system/usr/keylayout/sec_jack.kl \
	$(LOCAL_PATH)/system/usr/keylayout/sec_keypad.kl:system/usr/keylayout/sec_keypad.kl \
	$(LOCAL_PATH)/system/usr/keylayout/sec_touchscreen.kl:system/usr/keylayout/sec_touchscreen.kl \
	$(LOCAL_PATH)/system/usr/keylayout/libalsa-lib/libasound_module_pcm_ippvp.so:system/usr/lib/alsa-lib/libasound_module_pcm_ippvp.so \
	$(LOCAL_PATH)/system/usr/keylayout/libalsa-lib/libasound_module_pcm_vtrec.so:system/usr/lib/alsa-lib/libasound_module_pcm_vtrec.so \
	$(LOCAL_PATH)/system/usr/icu/icudt44l.dat:system/icu/icudt44l.dat \
	$(LOCAL_PATH)/system/usr/keychars/sec_touchscreen.kcm.bin:system/keychars/sec_touchscreen.kcm.bin 
